wandb:
  entity: williamberman

experiment:
    project: "muse"
    name: "styledrop-lora-dreambooth-2"
    output_dir: "styledrop-lora-dreambooth-2"
    max_train_examples: 3000000 # unused
    max_eval_examples: 20000 # unused
    save_every: 100
    generate_every: 100
    log_every: 50
    resume_from_checkpoint: False
    resume_lr_scheduler: True
    dont_resume_optimizer: True
    checkpoints_total_limit: 20
    is_lora: True

model:
    vq_model:
        type: "vqgan"
        pretrained: "openMUSE/vqgan-f16-8192-laion"
    
    text_encoder:
        type: "clip"
        pretrained: "openMUSE/clip-vit-large-patch14-text-enc"
        pad_token_id: 49407
    
    architecture: "uvit"

    transformer:
        vocab_size: 8256 # (8192 + 1 for <mask> = 8193 but 8256 is the next multiple of 8)
        hidden_size: 1024
        intermediate_size: 2816
        num_hidden_layers: 22
        num_attention_heads: 16
        in_channels: 768
        block_out_channels:
            - 768
        block_has_attention:
            - True
        block_num_heads: 12
        num_res_blocks: 3
        res_ffn_factor: 4
        patch_size: 1
        encoder_hidden_size: 768
        add_cross_attention: True
        project_encoder_hidden_states: True
        codebook_size: 8192
        num_vq_tokens: 1024
        initializer_range: 0.02
        norm_type: "rmsnorm"
        layer_norm_eps: 1e-6
        ln_elementwise_affine: True
        use_encoder_layernorm: False
        use_bias: False
        hidden_dropout: 0.0
        attention_dropout: 0.0
        use_codebook_size_for_output: True
        use_empty_embeds_for_uncond: True
        cond_embed_dim: 768
        micro_cond_encode_dim: 256
        micro_cond_embed_dim: 1280
        force_down_up_sample: True
        use_fused_residual_norm: True

    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: True
    pretrained_model_path: "openMUSE/diffusers-pipeline"
    pretrained_model_path_subfolder: "transformer"


dataset:
    type: "text2image"
    params:
        instance_data_root: "/fsx/william/cat_toy"
        instance_prompt: "A photo of sks toy"
        validation_prompts_file: "/fsx/william/dreambooth_prompts.txt"
        batch_size: ${training.batch_size}
        num_workers: 1
        resolution: 512
        pin_memory: False
        persistent_workers: False
    preprocessing:
        max_seq_length: 77
        resolution: 512
        center_crop: False
        random_flip: False


optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 0.0003
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8


lr_scheduler:
    scheduler: "constant_with_warmup"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 2000


training:
    gradient_accumulation_steps: 1
    batch_size: 6
    mixed_precision: "fp16"
    enable_tf32: True
    use_ema: False
    ema_decay: 0.9999
    ema_update_after_step: 0
    ema_update_every: 1
    seed: 9345104
    max_train_steps: 2000
    cond_dropout_prob: 0.0
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 8
    generation_timesteps: 16
    generation_temperature: 4.0
    use_stochastic_code: False
    soft_code_temp: 1.0
    mask_contiguous_region_prob: 0.0
    lora_r: 16
    lora_alpha: 32
    lora_target_modules: ["query", "key", "value"]